name: github-readme-snake

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_user_name: djokerbat   # الاسم الصحيح
          # لتغيير اللون، ممكن تضيف في args:
          args: --color blue
