name: github-readme-snake

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Dark Mode
        uses: Platane/snk@v3
        with:
          github_user_name: djokerbat
          outputs: |
            dist/github-snake-dark.svg?palette=github-dark
